In [2]:
import tensorflow as tf
import numpy as np

In [3]:

tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [4]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [5]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [6]:
tensor_bool = tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [7]:
tensor_string = tf.constant(["hello world","hi "])
print(tensor_string)

tf.Tensor([b'hello world' b'hi '], shape=(2,), dtype=string)


In [8]:
tensor_one_d = tf.constant([2,0.,-3,8,90],dtype=tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [9]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [10]:
tensor_three_d = tf.constant([
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
    [4,-3,32]],

])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [11]:
print(tensor_three_d.ndim)

3


In [12]:
print(tensor_three_d.shape)

(4, 2, 3)


In [13]:
t = tf.constant([[1, 1, 1], [2, 2, 2]],)
tf.size(t,out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [14]:
# shape of tensor 't' is [2, 2, 3]
t = tf.constant([[1, 1, 1], [2, 2, 2]])
tf.rank(t)  # 3

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [15]:
print(tf.shape(tensor_three_d))

tf.Tensor([4 2 3], shape=(3,), dtype=int32)


In [16]:
tensor_four_d = tf.constant([

[
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
    [4,-3,32]],

],

[
    [[13,26,0],
    [3,5,-12]],

    [[10,2,0],
    [1,0,23]],

    [[5,8,0],
    [2,73,0]],

    [[2,1,9],
    [4,-30,32]],

],

[
    [[103,26,0],
    [3,50,-12]],

    [[100,2,0],
    [1,0,23]],

    [[5,28,0],
    [2,3,0]],

    [[22,1,9],
    [44,-320,32]],

],

])
print(tensor_four_d)

tf.Tensor(
[[[[   1    2    0]
   [   3    5   -1]]

  [[  10    2    0]
   [   1    0    2]]

  [[   5    8    0]
   [   2    7    0]]

  [[   2    1    9]
   [   4   -3   32]]]


 [[[  13   26    0]
   [   3    5  -12]]

  [[  10    2    0]
   [   1    0   23]]

  [[   5    8    0]
   [   2   73    0]]

  [[   2    1    9]
   [   4  -30   32]]]


 [[[ 103   26    0]
   [   3   50  -12]]

  [[ 100    2    0]
   [   1    0   23]]

  [[   5   28    0]
   [   2    3    0]]

  [[  22    1    9]
   [  44 -320   32]]]], shape=(3, 4, 2, 3), dtype=int32)


In [17]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [18]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [19]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,4],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 4, 5, 5), dtype=float32)


In [20]:
fill_tensor = tf.fill(
    [1,3,4],5, name=None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


In [21]:
zeros_tensor = tf.zeros(
    [3,2],
    dtype=tf.dtypes.float32,
    name=None
)
print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [22]:
ones_tensor = tf.ones(
    [3,2],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [23]:
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(1, 3, 4), dtype=int32)


In [24]:
random_tensor = tf.random.normal(
    [3,2],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 99.819695  99.04971 ]
 [ 99.96036   99.25746 ]
 [101.32315   99.381454]], shape=(3, 2), dtype=float32)


In [25]:
random_tensor = tf.random.uniform(
    [5,5],
    minval=0,
    maxval=1000,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[597 764 960 558  70]
 [817 340 143 777 334]
 [632 429 283 664 894]
 [120 292 511 585 171]
 [601 294 650 406 833]], shape=(5, 5), dtype=int32)


In [26]:
tf.abs(tf.constant(-0.2))

<tf.Tensor: shape=(), dtype=float32, numpy=0.20000000298023224>

In [27]:
x_abs = tf.constant([-2.25, 3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [28]:
tf.sqrt((-2.25)**2 + 4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949020385742>

In [29]:
x = tf.constant(2+3j)
tf.abs(x)

<tf.Tensor: shape=(), dtype=float64, numpy=3.605551275463989>

In [30]:
tf.sqrt(2.0**2 + 3.0**2)

<tf.Tensor: shape=(), dtype=float32, numpy=3.605551242828369>

In [31]:
x = tf.constant([2, 3, 5, 7])
y = tf.constant([1, 2, 3, 4])
print(x+y)

tf.Tensor([ 3  5  8 11], shape=(4,), dtype=int32)


In [32]:
tf.add(x, y)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 3,  5,  8, 11], dtype=int32)>

In [33]:
z = tf.constant([1])
print(x+z)

tf.Tensor([3 4 6 8], shape=(4,), dtype=int32)


In [34]:
tf.add(x, z)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 4, 6, 8], dtype=int32)>

In [35]:
x = tf.constant([2, 3, 5, 7])
y = tf.constant([0, 2, 3, 4])
print(x/y)

tf.Tensor([       inf 1.5        1.66666667 1.75      ], shape=(4,), dtype=float64)


In [36]:
tf.math.divide_no_nan(x, y)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.        , 1.5       , 1.66666667, 1.75      ])>

In [37]:
tf.divide(x, y)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([       inf, 1.5       , 1.66666667, 1.75      ])>

In [38]:
x = tf.constant([2, 3, 4, 5])
y = tf.constant([[1], [3]])
tf.multiply(x, y)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 2,  3,  4,  5],
       [ 6,  9, 12, 15]], dtype=int32)>

In [45]:
x = tf.constant([2, 3, 5, 7])
y = tf.constant([3, 4, 6, 5])
tf.math.maximum(x, y)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 4, 6, 7], dtype=int32)>

In [48]:
tf.math.reduce_max(x)

<tf.Tensor: shape=(), dtype=int32, numpy=7>