In [1]:
import tensorflow as tf
import numpy as np

In [8]:
a = tf.constant([
    [7, 1, 4, 0, 2],
    [3, 4, 5, 3, 1],
    [0, 8, 6, 9, 7],
    [1, 1, 0, 2, 8]
 ])
b = tf.constant([
    [7, 1, 4, 0, 2],
    [3, 4, 5, 3, 1],
    [0, 8, 6, 9, 7],
    [1, 1, 0, 2, 8],
    [7, 8, 5, 9, 0],
 ])

tf.linalg.matmul(a, b)

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[ 66,  59,  67,  57,  43],
       [ 43,  70,  67,  72,  69],
       [ 82, 145, 111, 159, 122],
       [ 68,  71,  49,  79,  19]], dtype=int32)>

In [9]:
a@b

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[ 66,  59,  67,  57,  43],
       [ 43,  70,  67,  72,  69],
       [ 82, 145, 111, 159, 122],
       [ 68,  71,  49,  79,  19]], dtype=int32)>